language: node_js
node_js: stable

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - caodonghui777@gmail.com #你的邮箱地址
    on_success: change
    on_failure: always

# turn off the clone of submodules for change the SSH to HTTPS in .gitmodules to avoid the error
git:
  submodules: false

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "caodonghui"
  - git config user.email "caodonghui777@gmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
  global:
    # Github Pages
    - GH_REF: github.com/CaoDonghui123/caodonghui123.github.io.git
    # Coding Pages
    - CD_REF: git.coding.net/CaoDonghui123/caodonghui123.git